# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('event_time', models.TimeField(default=django.utils.timezone.now)),
                ('event_enable', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField(null=True)),
                ('event_poster', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'event_info',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='clients_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_infoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientlist.EventInfo'),
        ),
    ]
