# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_scheme_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'type_scheme',
            },
        ),
        migrations.AlterField(
            model_name='placeinfo',
            name='place_type_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientlist.TypeScheme'),
        ),
    ]
