# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0002_auto_20170317_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinfo',
            old_name='event_description',
            new_name='event_info_description',
        ),
        migrations.RenameField(
            model_name='eventinfo',
            old_name='event_name',
            new_name='event_info_name',
        ),
        migrations.RenameField(
            model_name='eventinfo',
            old_name='event_poster',
            new_name='event_info_poster',
        ),
    ]
