# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0002_auto_20170328_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='placescheme',
            name='place_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placescheme',
            name='place_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
