# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0003_auto_20170329_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeinfo',
            name='place_flag_set_sceme',
            field=models.BooleanField(default=False),
        ),
    ]
